"""
prepare_data.py - Stream Python source files from Hugging Face, filter lightly, tokenize
with the codeparrot BPE tokenizer, and write flat uint16 token streams:

    <out_dir>/train.bin   ~800M tokens (default)
    <out_dir>/val.bin     ~5M tokens, from a disjoint validation split
    <out_dir>/meta.json   token counts, tokenizer name, eos id
    <out_dir>/sample.txt  a decoded window, for eyeballing

Files are concatenated with <|endoftext|> between them; train.py samples random
512-token windows from the stream. Streaming means we never download the full ~50 GB.

Usage (Kaggle CPU notebook, Internet on):
    python data/prepare_data.py --out_dir /kaggle/working --train_tokens 800_000_000

Smaller for a quick test:
    python data/prepare_data.py --out_dir data/tiny --train_tokens 2_000_000 --val_tokens 200_000
"""

import argparse
import json
import os
import re
import sys
import time

import numpy as np

AUTOGEN_RE = re.compile(r"auto-?generated|do not edit|generated by", re.IGNORECASE)


def keep_file(text: str, max_chars: int) -> bool:
    """Light filters on top of codeparrot-clean's own cleaning."""
    n = len(text)
    if n < 100 or n > max_chars:
        return False
    lines = text.split("\n")
    if n / max(1, len(lines)) > 100:                     # minified / data dumps
        return False
    alpha = sum(c.isalpha() for c in text[:20000])
    if alpha / min(n, 20000) < 0.25:                      # mostly symbols/numbers
        return False
    if AUTOGEN_RE.search("\n".join(lines[:5])):
        return False
    return True


def tokenize_stream(dataset_name, split, tokenizer, target_tokens, out_path, max_chars, batch_files, log_every):
    from datasets import load_dataset

    eos = tokenizer.eos_token_id
    assert eos is not None, "tokenizer has no eos token"
    assert tokenizer.vocab_size <= 65536, "uint16 cannot hold this vocab"

    print(f"streaming {dataset_name} [{split}] -> {out_path} (target {target_tokens/1e6:.0f}M tokens)")
    ds = load_dataset(dataset_name, split=split, streaming=True)

    n_tokens = 0
    n_files = 0
    n_seen = 0
    buf = []
    batch = []
    t0 = time.time()
    with open(out_path, "wb") as f:
        def flush_batch():
            nonlocal n_tokens, n_files, buf
            if not batch:
                return
            enc = tokenizer(batch, add_special_tokens=False)["input_ids"]
            for ids in enc:
                ids.append(eos)
                buf.extend(ids)
                n_tokens += len(ids)
                n_files += 1
            batch.clear()
            if len(buf) >= 8_000_000:               # ~16 MB chunks
                np.asarray(buf, dtype=np.uint16).tofile(f)
                buf = []

        for ex in ds:
            n_seen += 1
            text = ex.get("content") or ex.get("code") or ""
            if not keep_file(text, max_chars):
                continue
            batch.append(text)
            if len(batch) >= batch_files:
                flush_batch()
                if n_files % log_every < batch_files:
                    rate = n_tokens / max(1e-9, time.time() - t0)
                    print(f"  {n_tokens/1e6:8.1f}M tokens | {n_files:,} files kept of {n_seen:,} seen "
                          f"| {rate/1e6:.2f}M tok/s | ETA {(target_tokens-n_tokens)/max(rate,1)/60:.1f} min",
                          flush=True)
            if n_tokens >= target_tokens:
                break
        flush_batch()
        if buf:
            np.asarray(buf, dtype=np.uint16).tofile(f)

    print(f"  done: {n_tokens:,} tokens from {n_files:,} files ({n_seen:,} seen) in {(time.time()-t0)/60:.1f} min")
    return n_tokens, n_files


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out_dir", default="data/pygpt-python-tokens")
    ap.add_argument("--tokenizer", default="codeparrot/codeparrot")
    ap.add_argument("--train_dataset", default="codeparrot/codeparrot-clean-train")
    ap.add_argument("--val_dataset", default="codeparrot/codeparrot-clean-valid")
    ap.add_argument("--train_tokens", type=int, default=800_000_000)
    ap.add_argument("--val_tokens", type=int, default=5_000_000)
    ap.add_argument("--max_chars", type=int, default=100_000)
    ap.add_argument("--batch_files", type=int, default=64)
    ap.add_argument("--log_every", type=int, default=2000)
    args = ap.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)
    os.environ.setdefault("TOKENIZERS_PARALLELISM", "true")

    from transformers import AutoTokenizer
    tok = AutoTokenizer.from_pretrained(args.tokenizer)
    print(f"tokenizer {args.tokenizer}: vocab {tok.vocab_size}, eos id {tok.eos_token_id}")

    # save the tokenizer next to the data so the app / eval can run offline
    tok.save_pretrained(os.path.join(args.out_dir, "tokenizer"))

    val_tokens, val_files = tokenize_stream(args.val_dataset, "train", tok, args.val_tokens,
                                            os.path.join(args.out_dir, "val.bin"), args.max_chars,
                                            args.batch_files, args.log_every)
    train_tokens, train_files = tokenize_stream(args.train_dataset, "train", tok, args.train_tokens,
                                                os.path.join(args.out_dir, "train.bin"), args.max_chars,
                                                args.batch_files, args.log_every)

    meta = dict(vocab_size=tok.vocab_size, tokenizer=args.tokenizer, eos_id=tok.eos_token_id,
                train_dataset=args.train_dataset, val_dataset=args.val_dataset,
                train_tokens=train_tokens, train_files=train_files,
                val_tokens=val_tokens, val_files=val_files, max_chars=args.max_chars)
    with open(os.path.join(args.out_dir, "meta.json"), "w") as f:
        json.dump(meta, f, indent=2)

    # round-trip check: decode a random window and make sure it looks like Python
    data = np.memmap(os.path.join(args.out_dir, "train.bin"), dtype=np.uint16, mode="r")
    start = np.random.randint(0, max(1, len(data) - 300))
    sample = tok.decode(data[start:start + 300].tolist())
    with open(os.path.join(args.out_dir, "sample.txt"), "w") as f:
        f.write(sample)
    print("\n--- decoded sample window (train.bin) ---")
    print(sample[:800])
    print("--- end sample ---")
    print(f"\nwrote {args.out_dir}: train.bin {os.path.getsize(os.path.join(args.out_dir,'train.bin'))/2**30:.2f} GB, "
          f"val.bin {os.path.getsize(os.path.join(args.out_dir,'val.bin'))/2**20:.1f} MB")


if __name__ == "__main__":
    sys.exit(main())
